### PR TITLE
Zap on invest and show instructions when no tokens

### PR DESCRIPTION
**Pull request by patcito**
implemented zap on /invest so that user can deposit from other tokens like on yearn.finance. It also converts to the vault token in the simulation box. We also show the status of the zap transaction which is pretty long (get gas price, approve transaction, deposit etc).

zap1sim

If no tokens are found in the wallet, rather than show the confusing input box, we explain to the user how to get the token, either on an exchange if it's a regular token (YFI, DAI etc) or if it's a curve token, we automatically link to the curve deposit vault to make it easier. See below image for crvUSDP. You can test in incognito mode or with no token in your metamask.

### CODE REVIEW

**Comment by antonnell** [comment]
Yo @patcito, sick PR bud. I'm going to test it a bit on my side, then have it deployed to prod if all is good.

**Comment by antonnell** [comment]
Depositing 3crv into the 3crv vault. When I hit deposit, I get 2 transactions. 

1 deposit into the vault contract (0x9cA85572E6A3EbF24dEDd195623F188735A5179f)
1 approval on the zap conteract (462991d18666c578f787e9ec0a74cd18d2971e5f)

I think you just need an "else" on line 67 on components/vaultActionCard/deposit.js

**Comment by antonnell** [comment]
Then I think, a nice value add would be to show whether the approval is needed before they hit deposit. (like how I have it on the vaults). Because I pressed Deposit, I signed the approval tx and waited. There's no real indication to the user that they have to press Deposit again to do the actual deposit.

image

**Comment by antonnell** [comment]
And if you want to be a real gangster, you can implement zap outs on withdraw as well.
I think zapping out is a massive value add for the site.

**Comment by patcito** [comment]
@antonnell thanks for the feedback I added the missing else, can you give it a try please?

Also in theory you don't need to click on deposit again as metamask should launch automatically. I'll have a look.

**Comment by antonnell** [comment]
@patcito did you submit a new PR or is it deployed somewhere that I can test?

I might have been too eager to wait for the 2nd TX to come up, perhaps we need to keep the button disabled with the spinner to show that there is more going to happen.

**Comment by antonnell** [comment]
image

@patcito 
I clicked on the balance of the token to input the full balance. Then on deposit, it returned that error.
Clicking on 25%, 50%, 75%, 100% also returns that error.
Manually typing an amount does work though.


Let me know if you want me to hop in and fix anything. I should have some time tomorrow.

**Comment by patcito** [comment]
Moved it here https://github.com/antonnell/yearn-finance/pull/18

**Pull request merged**
